import type { Metadata } from "next";
import { Manrope as Inter, Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Cursor from "@/components/Cursor";
import Aside from "@/components/Aside";
const inter = Manrope({ subsets: ["latin"] ,weight:"200"});

export const metadata: Metadata = {
  title: "E Kart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("dark", inter.className)}>
        <Header />
        <Cursor />
        <div className="grid grid-cols-12">
          <Aside />
          {children}
          {/* <Products /> */}
        </div>
      </body>
    </html>
  );
}
